version: "3.0"

services:
  mysql:
    build: 
      context: "." 
    container_name: $container_name
    hostname: $host_name
    ports: 
      - $Mysqlport:3306
    environment:
      MYSQL_ROOT_PASSWORD: $root_password
      MYSQL_DATABASE: $db_name
      MYSQL_USER: $user_name
      MYSQL_PASSWORD: $user_password
    entrypoint: 
      docker-entrypoint.sh
    command: 
      mysqld
      